### ISSUE TITLE
BT360 v10 seems to break the maintenance tasks

### ISSUE THREAD

**Issue by cordifed** [twinpiloot/BizTalk360-Maintenance-Tasks#3]
After upgrading to BizTalk 360 version 10.0, I have made the following observations:

- version check (string compare) fails because '10.0.3117.2607' is not greater than or equal to '9.1'
- API has breaking change in that sense that alertMaintenance must now have name and a comment, rather than only a comment

Are you willing to review and accept a pull request to mitigate this?

**Comment by cordifed** [comment]
Superseded by new versions 1.2.0/1.2.1; issue resolved

**Comment by RvdHorst1980** [comment]
@cordifed Have you solved the issue?
Because i can't see changes in the SetMaintenance.ps1 file.
And on the marketplace there is also an extension which you can use in a Release pipeline but this extension also misses information to make a correct call to the BizTalk360 api.

**Comment by twinpiloot** [comment]
I did not get a notification for this issue, but it has been solved now. And yes, you are welcome to create a PR for issues.
